// Tour-Daten Venedig → Roma, Ende August 2026
// Bergetappen-optimiert: keine Etappe über 200 km-Equivalent außer Königsetappe
const TOUR_META = {
  title: "La Strada del Sud",
  subtitle: "Venezia — Roma · in tredici giorni",
  year: "MMXXVI",
  startDate: "21 agosto 2026",
  endDate: "2 settembre 2026",
  totalKm: 620,
  totalHm: 6930,
  totalDays: 13,
  ridingDays: 11,
  restDays: 2,
};

// km-Equivalent = km + (hm / 100)
const STAGES = [
  {
    n: 1,
    date: "Ven 21.VIII",
    from: "Venezia (Mestre)",
    to: "Ferrara",
    km: 95,
    hm: 80,
    equiv: 103,
    profile: "pianura",
    asphalt: "A — perfetto",
    surface: "Argini del Po, ciclabile asfaltata, strade secondarie",
    note: "Flacher Auftakt durchs Po-Delta. Ciclovia Ven-To-Bo zu großen Teilen autofrei.",
    highlights: ["Chioggia (Caffè-Stopp)", "Adria", "Po-Delta", "Castello Estense Ferrara"],
    elevation: [10, 8, 5, 3, 2, 5, 12, 8, 6, 9, 14, 10, 8, 12, 15],
    sleep: {
      name: "Locanda della Luna",
      type: "Boutique-Locanda",
      area: "Ferrara centro storico",
      vibe: "Renaissance-Palazzo, Innenhof, gehobene Küche",
      price: "€140–180",
    },
    dinner: {
      name: "Trattoria da Noemi",
      cuisine: "Ferrarese · Cappellacci di zucca, Salama da sugo",
      stars: "Slow Food Snail · 1 Gabel Gambero Rosso",
    },
  },
  {
    n: 2,
    date: "Sab 22.VIII",
    from: "Ferrara",
    to: "Bologna",
    km: 55,
    hm: 150,
    equiv: 70,
    profile: "pianura",
    asphalt: "A — perfetto",
    surface: "Strade provinciali, ultimi km su ciclabile",
    note: "Kurze Etappe — entspannt nach Bologna rollen, Nachmittag in der Stadt.",
    highlights: ["Cento", "Pieve di Cento", "Piazza Maggiore"],
    elevation: [10, 12, 14, 18, 22, 28, 35, 42, 38, 45, 52, 60, 68, 72, 78],
    sleep: {
      name: "Palazzo Trevi Charming House",
      type: "Design-B&B im Palazzo",
      area: "Bologna · zwischen Due Torri & Piazza Maggiore",
      vibe: "Hohe Decken, Fresken, Espresso-Bar im Hof",
      price: "€160–200",
    },
    dinner: {
      name: "Trattoria di Via Serra",
      cuisine: "Bolognese DOC · Tagliatelle al ragù, Tortellini in brodo",
      stars: "Slow Food Snail · stadtweit beste Tagliatelle",
    },
  },
  {
    n: 3,
    date: "Dom 23.VIII",
    from: "Bologna",
    to: "Monzuno",
    km: 45,
    hm: 1000,
    equiv: 145,
    profile: "montagna — Apennin-Auftakt",
    asphalt: "A — perfetto",
    surface: "SP325 ruhig, Sonntagsstrecke",
    note: "Beine an den Apennin gewöhnen. Kurze, knackige Etappe — bewusst kein km-Fresser, weil die hm es in sich haben.",
    highlights: ["Pianoro", "Monte delle Formiche", "Monzuno (623 m)"],
    elevation: [80, 140, 220, 320, 420, 520, 580, 540, 480, 540, 600, 580, 620, 640, 623],
    climb: { name: "Monzuno", length: "12 km", grade: "4,5 % medio · 7 % max", altitude: "623 m" },
    sleep: {
      name: "Agriturismo Le Valli",
      type: "Agriturismo · Pool, Weinberg",
      area: "Monzuno · Apennin-Hänge",
      vibe: "Steinhaus, Cantina, Abendessen unterm Feigenbaum",
      price: "€120–150 HP",
    },
    dinner: {
      name: "Hauseigenes Ristorante",
      cuisine: "Bolognese rurale · Tortelloni, eigener Wein",
      stars: "Slow Food empfohlen",
    },
  },
  {
    n: 4,
    date: "Lun 24.VIII",
    from: "Monzuno",
    to: "Firenze",
    km: 70,
    hm: 1250,
    equiv: 195,
    queen: true,
    profile: "tappa regina — Raticosa + Futa",
    asphalt: "A — perfetto, SS65 rifatta 2024",
    surface: "SS65 Storica della Futa — heilige Giro-Strecke",
    note: "Königsetappe. Zwei Pässe an einem Tag: Raticosa (968 m) + Futa (903 m). Früh starten, Nachmittag Florenz.",
    highlights: ["Passo della Raticosa 968 m", "Passo della Futa 903 m", "Cimitero Militare Germanico", "San Piero a Sieve", "Ponte Vecchio"],
    elevation: [623, 720, 820, 920, 968, 880, 760, 820, 903, 820, 640, 460, 280, 140, 50],
    climb: { name: "Raticosa + Futa", length: "30 km gesamt", grade: "5 % medio", altitude: "968 m / 903 m" },
    sleep: {
      name: "Soprarno Suites",
      type: "Boutique-Hotel im Oltrarno",
      area: "Firenze · südlich Ponte Vecchio",
      vibe: "Antike Möbel, Bibliothek, ruhige Gasse",
      price: "€220–280",
    },
    dinner: {
      name: "Trattoria Cammillo",
      cuisine: "Toscana classica · Bistecca alla Fiorentina",
      stars: "Institution seit 1945",
    },
  },
  {
    n: 5,
    date: "Mar 25.VIII",
    from: "Firenze",
    to: "Firenze",
    km: 0,
    hm: 0,
    equiv: 0,
    profile: "riposo",
    rest: true,
    note: "Ruhetag in Florenz. Beine hoch, Augen auf.",
    highlights: ["Uffizien (Reservierung!)", "Duomo + Cupola Brunelleschi", "Boboli-Gärten", "Mercato Centrale", "Aperitivo Piazzale Michelangelo"],
    sleep: {
      name: "Soprarno Suites",
      type: "(zweite Nacht)",
      area: "Firenze",
      vibe: "—",
      price: "—",
    },
    dinner: {
      name: "Il Santo Bevitore",
      cuisine: "Toscana moderna · Oltrarno",
      alt: "Special: Enoteca Pinchiorri ★★★",
      stars: "1 Gabel Gambero Rosso",
    },
  },
  {
    n: 6,
    date: "Mer 26.VIII",
    from: "Firenze",
    to: "Greve in Chianti",
    km: 45,
    hm: 800,
    equiv: 125,
    profile: "collinare — Chianti Nord",
    asphalt: "A — perfetto, panoramica",
    surface: "SR222 Chiantigiana — Postkartenstrecke",
    note: "Halbe Chiantigiana. Bewusst kurz, damit Mittag in Panzano bei Cecchini reicht.",
    highlights: ["Impruneta", "Strada in Chianti", "Greve in Chianti", "Antica Macelleria Cecchini in Panzano (Pflicht!)"],
    elevation: [50, 180, 240, 320, 380, 420, 360, 440, 480, 420, 380, 340, 320, 280, 240],
    sleep: {
      name: "Villa Bordoni",
      type: "Boutique-Villa · 16. Jh.",
      area: "Greve in Chianti · Hügellage",
      vibe: "Pool im Olivenhain, Glyzinien-Pergola, eigene Cantina",
      price: "€240–300",
    },
    dinner: {
      name: "Ristorante Villa Bordoni",
      cuisine: "Toscana raffinata · Tasting-Menü mit Chianti-Pairing",
      stars: "Gambero Rosso · Wine Spectator",
    },
  },
  {
    n: 7,
    date: "Gio 27.VIII",
    from: "Greve in Chianti",
    to: "Siena",
    km: 45,
    hm: 700,
    equiv: 115,
    profile: "collinare — Chianti Süd",
    asphalt: "A — perfetto",
    surface: "SR222 + SP102 — wenig Verkehr",
    note: "Zweite Hälfte der Chiantigiana. Castelli, Zypressen, Ankunft auf der Piazza del Campo.",
    highlights: ["Castellina in Chianti", "Radda in Chianti", "Castelnuovo Berardenga", "Ankunft Piazza del Campo"],
    elevation: [240, 380, 460, 520, 480, 540, 460, 380, 420, 360, 340, 380, 320, 340, 322],
    sleep: {
      name: "Campo Regio Relais",
      type: "Boutique-Relais · 6 Suiten",
      area: "Siena · 3 Min vom Campo",
      vibe: "Terrasse mit Blick auf Duomo, Frühstück auf der Loggia",
      price: "€280–340",
    },
    dinner: {
      name: "Osteria Le Logge",
      cuisine: "Senese moderna · Pici al ragù, Tartare di Chianina",
      stars: "Gambero Rosso · Wine Spectator",
    },
  },
  {
    n: 8,
    date: "Ven 28.VIII",
    from: "Siena",
    to: "Siena",
    km: 0,
    hm: 0,
    equiv: 0,
    profile: "riposo",
    rest: true,
    note: "Ruhetag Siena. Mittelalterliche Stille.",
    highlights: ["Piazza del Campo", "Duomo + Libreria Piccolomini", "Torre del Mangia (88 m hoch)", "Pinacoteca", "Brunello-Tasting Montalcino (optional)"],
    sleep: {
      name: "Campo Regio Relais",
      type: "(zweite Nacht)",
      area: "Siena",
      vibe: "—",
      price: "—",
    },
    dinner: {
      name: "Enoteca I Terzi",
      cuisine: "Senese · Riesige Brunello-Karte",
      stars: "Slow Food",
    },
  },
  {
    n: 9,
    date: "Sab 29.VIII",
    from: "Siena",
    to: "Pienza",
    km: 60,
    hm: 850,
    equiv: 145,
    profile: "collinare — Val d'Orcia",
    asphalt: "A — perfetto",
    surface: "SR2 Cassia + SP146 (wir bleiben auf Asphalt!)",
    note: "Val d'Orcia. UNESCO. Zypressenalleen wie auf Postkarten — weil die Postkarten hier fotografiert wurden.",
    highlights: ["Buonconvento", "San Quirico d'Orcia", "Bagno Vignoni (Thermalbad-Stopp!)", "Pienza"],
    elevation: [322, 280, 220, 180, 240, 320, 380, 290, 220, 280, 360, 440, 491, 480, 491],
    sleep: {
      name: "Agriturismo La Bandita",
      type: "Agriturismo · Pool, Weinberg, Spa",
      area: "Pienza · zwischen Cipressen",
      vibe: "Designhotel-Niveau, Sterne-Restaurant, Pool mit Val-d'Orcia-Blick",
      price: "€280–380 HP",
    },
    dinner: {
      name: "Ristorante La Bandita Townhouse",
      cuisine: "Toscana contemporanea · degustazione 5 portate",
      stars: "Gambero Rosso · Condé Nast Top 50",
    },
  },
  {
    n: 10,
    date: "Dom 30.VIII",
    from: "Pienza",
    to: "Acquapendente",
    km: 65,
    hm: 900,
    equiv: 155,
    profile: "collinare — Monte Amiata-Region",
    asphalt: "A/B — meist gut, einzelne raue Abschnitte",
    surface: "SR2 Cassia — historische Römerstraße",
    note: "Über Radicofani (Burg auf 814 m, das Highlight). Danach Abfahrt Richtung Latium.",
    highlights: ["San Quirico", "Salita Radicofani 814 m", "Acquapendente"],
    elevation: [491, 540, 620, 720, 814, 760, 640, 520, 420, 380, 460, 420, 380, 410, 420],
    climb: { name: "Salita di Radicofani", length: "10 km", grade: "5 % medio · 9 % max", altitude: "814 m" },
    sleep: {
      name: "La Casa di Campagna",
      type: "Agriturismo · Olivenhain & Pool",
      area: "Acquapendente · Hügel über dem Lago di Bolsena",
      vibe: "Toskana-Latium-Grenze, ruhig, Familienbetrieb",
      price: "€110–140 HP",
    },
    dinner: {
      name: "La Stiaccia",
      cuisine: "Tuscia · Pici alla Carbonara di lago, Pecorino-Auswahl",
      stars: "Slow Food empfohlen",
    },
  },
  {
    n: 11,
    date: "Lun 31.VIII",
    from: "Acquapendente",
    to: "Sutri",
    km: 75,
    hm: 600,
    equiv: 135,
    profile: "collinare — Tuscia",
    asphalt: "A — meist gut",
    surface: "SR2 Cassia, ruhig",
    note: "Etruskerland. Tuffstein-Städte, Vulkanseen, weniger Touristen.",
    highlights: ["Bolsena (Lago di Bolsena, Caffè-Stopp)", "Montefiascone (Est! Est!! Est!!!)", "Viterbo (Papstpalast)", "Vetralla", "Sutri"],
    elevation: [420, 380, 348, 420, 560, 640, 580, 480, 420, 360, 320, 380, 460, 380, 291],
    sleep: {
      name: "Le Querce di Mamre",
      type: "Agriturismo · Olivenhain",
      area: "Sutri · ruhige Hügellage",
      vibe: "Familiengeführt, eigenes Olivenöl, Pool, riesiger Garten",
      price: "€110–140 HP",
    },
    dinner: {
      name: "Hauseigene Cucina",
      cuisine: "Viterbese · Acquacotta, Abbacchio, eigener Wein",
      stars: "Slow Food empfohlen",
    },
  },
  {
    n: 12,
    date: "Mar 1.IX",
    from: "Sutri",
    to: "Roma",
    km: 65,
    hm: 600,
    equiv: 125,
    profile: "collinare verso Roma",
    asphalt: "A — bis 20 km vor Rom, dann Via Cassia",
    surface: "Via Cassia letzte 25 km — Verkehr nimmt zu, früh starten!",
    note: "Letzte Etappe. Von der Cassia herabrollen — und plötzlich der Petersdom.",
    highlights: ["Campagnano", "Lago di Bracciano (Abstecher)", "La Storta", "Eintritt Roma · Piazza del Popolo"],
    elevation: [291, 360, 420, 380, 320, 280, 220, 180, 140, 100, 80, 60, 40, 30, 20],
    sleep: {
      name: "Hotel Vilòn",
      type: "Boutique-Palazzo · 18. Jh.",
      area: "Roma · Via dell'Arancio (zwischen Spanischer Treppe & Tiber)",
      vibe: "Geheimer Eingang, Cortile mit Glyzinien, Sterne-Restaurant",
      price: "€340–420",
    },
    dinner: {
      name: "Adelaide Ristorante (im Hotel)",
      cuisine: "Romana moderna",
      alt: "Alternative: Roscioli — Cacio e Pepe Legende",
      stars: "1 Stern Michelin / Roscioli: Slow Food",
    },
  },
  {
    n: 13,
    date: "Mer 2.IX",
    from: "Roma Termini",
    to: "München Hbf",
    km: 0,
    hm: 0,
    equiv: 0,
    profile: "treno",
    train: true,
    note: "Bahn-Rückfahrt mit Fahrradticket.",
    highlights: [
      "08:35 Frecciarossa Roma Termini → Bologna (3:00h, Rad in Fahrradabteil — Reservierung Pflicht!)",
      "12:25 EC 88 Bologna → München (Verona · Brenner · München, ~7:30h)",
      "Ankunft München Hbf ca. 19:55",
      "Fahrradticket Italien: Trenitalia €12 Frecciarossa-Aufpreis · DB·ÖBB EC: €15",
    ],
  },
];

const COSTS = [
  { item: "Übernachtungen (12 Nächte, im DZ pro Person)", amount: 1280 },
  { item: "Halbpension / Abendessen", amount: 520 },
  { item: "Caffè · Pranzo · Gelato unterwegs", amount: 240 },
  { item: "Eintritte Florenz + Siena", amount: 90 },
  { item: "Bahnticket Roma → München + Fahrradticket", amount: 145 },
  { item: "Reserve / Werkstatt / Notfall", amount: 150 },
];
const COSTS_TOTAL = COSTS.reduce((s, c) => s + c.amount, 0);

window.TOUR_META = TOUR_META;
window.STAGES = STAGES;
window.COSTS = COSTS;
window.COSTS_TOTAL = COSTS_TOTAL;
